<x-app-layout><div class="kb-shell">@include('admin.curriculum._styles')<div class="kb-wrap">
<div class="kb-crumb"><a href="{{ route('admin.curriculum') }}">Courses</a><span>›</span><strong>{{ $course->title }}</strong></div>
<div class="kb-top"><div><div class="kb-title">{{ $course->title }}</div><div class="kb-muted">Manage only the five learning sections here.</div></div><form class="kb-search"><input class="kb-input" name="q" value="{{ $search }}" placeholder="Search section"><button class="kb-btn kb-dark">Search</button></form></div>
@include('admin.curriculum._flash')
<section class="kb-card kb-pad" style="margin-bottom:18px"><div class="kb-section-head"><h3 style="font-weight:900;font-size:18px">Course settings</h3></div><form method="POST" action="{{ route('admin.curriculum.courses.update',$course) }}" class="kb-form-grid">@csrf @method('PUT')<input class="kb-input" name="title" value="{{ $course->title }}" required><input class="kb-input" name="level" value="{{ $course->level }}" required><input class="kb-input" name="description" value="{{ $course->description }}"><label><input type="checkbox" name="is_published" value="1" @checked($course->is_published)> Published</label><button class="kb-btn kb-primary">Save Course</button></form></section>
<details class="kb-card kb-pad kb-modal"><summary class="kb-btn kb-primary">＋ Add section</summary><form method="POST" action="{{ route('admin.curriculum.courses.sections.store',$course) }}" class="kb-form-two" style="margin-top:16px">@csrf<input class="kb-input" name="icon" placeholder="📖"><input class="kb-input" name="name" required placeholder="Vocabulary, Kanji, Grammar..."><button class="kb-btn kb-primary">Add Section</button></form></details>
<div class="kb-grid">@forelse($sections as $section)<article class="kb-card kb-item"><div class="kb-row"><div class="kb-icon">{{ $section->icon ?: '📘' }}</div><div class="kb-actions">@include('admin.curriculum._move',['type'=>'section','id'=>$section->id])</div></div><h2 style="font-size:20px;font-weight:900;margin:14px 0 5px">{{ $section->name }}</h2><div class="kb-stat">{{ $section->modules_count }} modules · {{ $section->lessons_count }} lessons</div><div style="margin-top:16px"><a class="kb-btn kb-primary" href="{{ route('admin.curriculum.sections.show',$section) }}">Open section →</a></div></article>@empty<div class="kb-card kb-empty" style="grid-column:1/-1">No sections found.</div>@endforelse</div>
<form method="POST" action="{{ route('admin.curriculum.courses.destroy',$course) }}" onsubmit="return confirm('Delete this whole course and all content?')" style="margin-top:24px">@csrf @method('DELETE')<button class="kb-btn kb-danger">Delete entire course</button></form>
</div></div></x-app-layout>
