<x-app-layout><div class="kb-shell">@include('admin.curriculum._styles')<div class="kb-wrap">
<div class="kb-crumb"><a href="{{ route('admin.curriculum') }}">Courses</a><span>›</span><a href="{{ route('admin.curriculum.courses.show',$lesson->module->section->course) }}">{{ $lesson->module->section->course->title }}</a><span>›</span><a href="{{ route('admin.curriculum.sections.show',$lesson->module->section) }}">{{ $lesson->module->section->name }}</a><span>›</span><a href="{{ route('admin.curriculum.modules.show',$lesson->module) }}">{{ $lesson->module->title }}</a><span>›</span><strong>Edit lesson</strong></div>
<div class="kb-top"><div><div class="kb-title">Edit Lesson</div><div class="kb-muted">{{ $lesson->title }}</div></div><a class="kb-btn kb-soft" href="{{ route('admin.curriculum.modules.show',$lesson->module) }}">← Back to lessons</a></div>
@include('admin.curriculum._flash')
<form class="kb-card kb-pad kb-editor" method="POST" action="{{ route('admin.curriculum.lessons.update',$lesson) }}">@csrf @method('PUT')
<div><label class="kb-stat">Lesson title</label><input class="kb-input" name="title" value="{{ old('title',$lesson->title) }}" required></div><div><label class="kb-stat">Minutes</label><input class="kb-input" type="number" min="1" name="estimated_minutes" value="{{ old('estimated_minutes',$lesson->estimated_minutes) }}"></div><div><label class="kb-stat">XP reward</label><input class="kb-input" type="number" min="0" name="xp_reward" value="{{ old('xp_reward',$lesson->xp_reward) }}"></div><div><label class="kb-stat">Status</label><select class="kb-select" name="status"><option value="published" @selected(old('status',$lesson->status)==='published')>Published</option><option value="draft" @selected(old('status',$lesson->status)==='draft')>Draft</option></select></div>
<div class="wide"><label class="kb-stat">Lesson content</label><textarea class="kb-textarea" name="content">{{ old('content',$lesson->content) }}</textarea></div><button class="kb-btn kb-primary wide">Save Lesson</button></form>
<form method="POST" action="{{ route('admin.curriculum.lessons.destroy',$lesson) }}" onsubmit="return confirm('Delete this lesson permanently?')" style="margin-top:18px">@csrf @method('DELETE')<button class="kb-btn kb-danger">Delete lesson</button></form>
</div></div></x-app-layout>
