<x-app-layout><div class="kb-shell">@include('admin.curriculum._styles')<div class="kb-wrap">
<div class="kb-crumb"><a href="{{ route('admin.curriculum') }}">Courses</a><span>›</span><a href="{{ route('admin.curriculum.courses.show',$module->section->course) }}">{{ $module->section->course->title }}</a><span>›</span><a href="{{ route('admin.curriculum.sections.show',$module->section) }}">{{ $module->section->name }}</a><span>›</span><strong>{{ $module->title }}</strong></div>
<div class="kb-top"><div><div class="kb-title">{{ $module->title }}</div><div class="kb-muted">Only lessons from this module are shown.</div></div><form class="kb-search"><input class="kb-input" name="q" value="{{ $search }}" placeholder="Search lesson"><select class="kb-select" name="status"><option value="all">All</option><option value="published" @selected($status==='published')>Published</option><option value="draft" @selected($status==='draft')>Draft</option></select><button class="kb-btn kb-dark">Filter</button></form></div>
@include('admin.curriculum._flash')
<section class="kb-card kb-pad" style="margin-bottom:18px"><form method="POST" action="{{ route('admin.curriculum.modules.update',$module) }}" class="kb-form-two">@csrf @method('PUT')<input class="kb-input" name="title" value="{{ $module->title }}" required><input class="kb-input" name="description" value="{{ $module->description }}"><button class="kb-btn kb-primary">Save Module</button></form></section>
<details class="kb-card kb-pad kb-modal"><summary class="kb-btn kb-primary">＋ Create lesson</summary><form method="POST" action="{{ route('admin.curriculum.modules.lessons.store',$module) }}" class="kb-editor" style="margin-top:16px">@csrf<input class="kb-input" name="title" required placeholder="Lesson title"><input class="kb-input" type="number" min="1" name="estimated_minutes" value="10" title="Minutes"><input class="kb-input" type="number" min="0" name="xp_reward" value="10" title="XP"><select class="kb-select" name="status"><option value="published">Published</option><option value="draft">Draft</option></select><textarea class="kb-textarea wide" name="content" placeholder="Lesson content"></textarea><button class="kb-btn kb-primary wide">Create and open editor</button></form></details>
<div class="kb-list">@forelse($lessons as $lesson)<article class="kb-card kb-list-item"><div class="kb-row"><div><div class="kb-actions"><h3 style="font-size:17px;font-weight:900">{{ $lesson->position + 1 }}. {{ $lesson->title }}</h3><span class="kb-badge {{ $lesson->status==='published'?'kb-published':'kb-draft' }}">{{ ucfirst($lesson->status) }}</span></div><div class="kb-stat" style="margin-top:7px">{{ $lesson->estimated_minutes }} min · {{ $lesson->xp_reward }} XP</div></div><div class="kb-actions">@include('admin.curriculum._move',['type'=>'lesson','id'=>$lesson->id])<a class="kb-btn kb-primary" href="{{ route('admin.curriculum.lessons.edit',$lesson) }}">Edit →</a><form method="POST" action="{{ route('admin.curriculum.lessons.destroy',$lesson) }}" onsubmit="return confirm('Delete this lesson?')">@csrf @method('DELETE')<button class="kb-btn kb-danger">Delete</button></form></div></div></article>@empty<div class="kb-card kb-empty">No lessons found.</div>@endforelse</div><div class="kb-pagination">{{ $lessons->links() }}</div>
<form method="POST" action="{{ route('admin.curriculum.modules.destroy',$module) }}" onsubmit="return confirm('Delete this module and all lessons?')" style="margin-top:24px">@csrf @method('DELETE')<button class="kb-btn kb-danger">Delete module</button></form>
</div></div></x-app-layout>
