<x-app-layout><div class="kb-shell">@include('admin.curriculum._styles')<div class="kb-wrap">
<div class="kb-crumb"><a href="{{ route('admin.curriculum') }}">Courses</a><span>›</span><a href="{{ route('admin.curriculum.courses.show',$section->course) }}">{{ $section->course->title }}</a><span>›</span><strong>{{ $section->name }}</strong></div>
<div class="kb-top"><div><div class="kb-title">{{ $section->icon }} {{ $section->name }}</div><div class="kb-muted">Open one module to manage its lessons.</div></div><form class="kb-search"><input class="kb-input" name="q" value="{{ $search }}" placeholder="Search module"><button class="kb-btn kb-dark">Search</button></form></div>
@include('admin.curriculum._flash')
<section class="kb-card kb-pad" style="margin-bottom:18px"><form method="POST" action="{{ route('admin.curriculum.sections.update',$section) }}" class="kb-form-two">@csrf @method('PUT')<input class="kb-input" name="icon" value="{{ $section->icon }}"><input class="kb-input" name="name" value="{{ $section->name }}" required><button class="kb-btn kb-primary">Save Section</button></form></section>
<details class="kb-card kb-pad kb-modal"><summary class="kb-btn kb-primary">＋ Add module</summary><form method="POST" action="{{ route('admin.curriculum.sections.modules.store',$section) }}" class="kb-form-two" style="margin-top:16px">@csrf<input class="kb-input" name="title" required placeholder="Module title"><input class="kb-input" name="description" placeholder="Short description"><button class="kb-btn kb-primary">Add Module</button></form></details>
<div class="kb-list">@forelse($modules as $module)<article class="kb-card kb-list-item"><div class="kb-row"><div><h3 style="font-size:18px;font-weight:900">{{ $module->title }}</h3><div class="kb-muted">{{ $module->description ?: 'No description' }}</div><div class="kb-stat" style="margin-top:7px">{{ $module->lessons_count }} lessons</div></div><div class="kb-actions">@include('admin.curriculum._move',['type'=>'module','id'=>$module->id])<a class="kb-btn kb-primary" href="{{ route('admin.curriculum.modules.show',$module) }}">Open →</a></div></div></article>@empty<div class="kb-card kb-empty">No modules found.</div>@endforelse</div>
<form method="POST" action="{{ route('admin.curriculum.sections.destroy',$section) }}" onsubmit="return confirm('Delete this section and all modules?')" style="margin-top:24px">@csrf @method('DELETE')<button class="kb-btn kb-danger">Delete section</button></form>
</div></div></x-app-layout>
